apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "test"
  namespace: "dev"
  labels:
    app: "test"
  annotations:
    timestamp: "20230123T130111"
    deployment_number: "$19"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: "100%"
      maxUnavailable: "5%"
    type: "RollingUpdate"
  minReadySeconds: 0
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: "test"
  template:
    metadata:
      labels:
        app: "test"
    spec:
      serviceAccountName: "test"
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: "ot-nexus-regcred"
      containers:
        - name: "test"
          image: "registry.buildpiper.in/ot-micro-frontend-stage:${BP_IMAGE_TAG}ss"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
              protocol: "TCP"
              name: "ot-emp-ui"
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "test"
  namespace: "dev"
  labels:
    app: "test"
spec:
  type: "ClusterIP"
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      name: "ot-emp-ui"
  selector:
    app: "test"
